# This is to get the CDS sequence for 118 organisms except Sea Urchin since that is a part of Ensembl Metazoa.
# Here I read the ids generated by the per program and get the CDS one by one for each organism. All this is 
# based on Ensembl version 75. 
#
# The name of biomaRt variables are standard and can be looked into biomaRt package help.
#
# For each organism -- change the 3 things below:
#  (1) The name of biomart......................... line 14
#  (2) name of column for ids...................... line 24 and 26
#  (3) output filename............................. line 28
#  

library("biomaRt")
setwd("C:\\Users\\Param\\Desktop\\Desktop_Stuff\\Analysis\\genome_sequences\\biomart_download_cds") # set it to your working directory

ensembl = useMart("ensembl", "mmusculus_gene_ensembl")

# Read Ids and split to get list of peptide ids in an R variable
inlist <- strsplit(readLines("prot_id_file.txt"), "[[:space:]]+")
ids <- lapply(inlist, tail, n = -1)
names(ids) <- lapply(inlist, head, n = 1)

# remove inlist to free some space
rm(inlist)

for (i in 1:length(ids$mmusculus)) { # foreach peptide id for this organism
  
  seq = getSequence(id = ids$mmusculus[i], type="ensembl_peptide_id",seqType="coding", mart=ensembl) # get seqquence
  
  write.table(seq[2:1], file = "mmusculus.fasta", append=T, col.names=F, quote = F,row.names = F, sep = "\n") # write out
   
  show(i)
}


# Remove the variables for next one
rm("ensembl","i","ids","seq")

